[package]
name = "rumpus_driver"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = "4.5.43"
image = "0.25.6"
nalgebra = "0.34.0"
rand = "0.9.2"
rumpus = { path = "../rumpus" }
